name: Generate RSS Feed

on:
  schedule:
    - cron: '10 1 * * *'  # JST 10:10毎日実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build RSS from Shigahochi
        run: |
          python rss_generator.py

      - name: Commit & push if changed
        run: |
          if [ ! -f rss.xml ]; then
            echo "rss.xml not found. Nothing to commit. Exiting normally."
            exit 0
          fi
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add rss.xml
          git commit -m "Update Shigahochi RSS" || echo "Nothing to commit"
          git push
